name: Pull and Clean Tickers

on:
  schedule:
    - cron: '20 0 * * *'  # Runs every day at 12:20 AM UTC
  workflow_dispatch:  # Enable manual trigger

jobs:
  update-tickers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Delete existing dataset files (if any)
      run: |
        rm -f nyse_tickers.txt nasdaq_tickers.txt

    - name: Pull NYSE tickers
      run: |
        wget https://raw.githubusercontent.com/rreichel3/US-Stock-Symbols/main/nyse/nyse_tickers.txt -O nyse_tickers.txt

    - name: Pull NASDAQ tickers
      run: |
        wget https://raw.githubusercontent.com/rreichel3/US-Stock-Symbols/main/nasdaq/nasdaq_tickers.txt -O nasdaq_tickers.txt

  clean-datasets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run Python script to clean tickers
      run: |
        python clean_datasets.py update-tickers/nyse_tickers.txt
        python clean_datasets.py update-tickers/nasdaq_tickers.txt

    - name: Add cleaned dataset CSVs
      run: |
        git add nyse_tickers_cleaned.csv nasdaq_tickers_cleaned.csv

    - name: Commit and push changes
      run: |
        git config --global user.email "jpnewman167@gmail.com"
        git config --global user.name "JNewman-cell"
        git commit -m "Add cleaned dataset CSVs"
        git push origin main
