name: Generate requirements.txt

on:
  workflow_dispatch:

jobs:
  generate_requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
  
      - name: Install pipreqs
        run: pip install pipreqs

      - name: Generate requirements.txt
        run: pipreqs . --force

      - name: Check for changes in the requirements file
        run: |
          git diff requirements.txt
  
      - name: Commit changes
        run: |
          git config --global user.email "jpnewman167@gmail.com"
          git config --global user.name "JNewman-cell"
          git add ./requirements.txt
          git commit -m "Add cleaned dataset CSVs and Trie pickle"
          git push origin main
