name: Generate requirements.txt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
  
      - name: Install pipreqs
        run: pip install pipreqs

      - name: Generate requirements.txt
        run: pipreqs . --force
  
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add requirements.txt
          git commit -m "Update requirements.txt" || echo "No changes to commit"
