name: Test Custom Trie Autocomplete

on:
  schedule:
    - cron: '20 * * * 0'  # Runs every Sunday at 12:20 AM PST
  workflow_dispatch:  # Enable manual trigger

jobs:
  verify-validity-of-custom-trie:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Test Custom Trie Autocomplete
      run: |
        cd FlaskApp
        python test_Trie.py
